sudo: required

services:
    - docker

before_install:
    -  docker build -t stwalez/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run stwalez/react-test npm test -- --coverage

after_success:
    - docker build -t stwalez/multi-client ./client
    - docker build -t stwalez/multi-nginx ./nginx
    - docker build -t stwalez/multi-server ./server
    - docker build -t stwalez/multi-worker ./worker

    # Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push stwalez/multi-client
    - docker push stwalez/multi-nginx
    - docker push stwalez/multi-server
    - docker push stwalez/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-727708957863
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


